name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore src/Pepegov.MicroserviceFramework/Pepegov.MicroserviceFramework.sln
    - name: Build
      run: dotnet build src/Pepegov.MicroserviceFramework/Pepegov.MicroserviceFramework.sln --configuration Release --no-restore 
    - name: Publish Pepegov.MicroserviceFramework
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Pepegov.MicroserviceFramework/Pepegov.MicroserviceFramework/Pepegov.MicroserviceFramework.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
    - name: Publish Pepegov.MicroserviceFramework.ApiResults
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Pepegov.MicroserviceFramework/Pepegov.MicroserviceFramework.ApiResults/Pepegov.MicroserviceFramework.ApiResults.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Pepegov.MicroserviceFramework.AspNetCore
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Pepegov.MicroserviceFramework/Pepegov.MicroserviceFramework.AspNetCore/Pepegov.MicroserviceFramework.AspNetCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}